trigger:
- master

stages:
- stage: Build
  displayName: 'Build And Test'
  jobs:
  - job: Build
    displayName: 'Build And Test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet build
      displayName: 'Build Code'
    - script: dotnet test
      displayName: 'Run Tests'
    - task: CopyFiles@1
      displayName: 'Copy NUPKG To Staging'
      inputs:
        SourceFolder: $(Build.SourcesDirectory)/src/bin/Debug
        TargetFolder: $(Build.StagingDirectory)
        Contents: '*.nupkg'
    - publish: $(Build.StagingDirectory)
      displayName: 'Publish NUPKG As Artifact'
      artifact: nupkg